### ISSUE TITLE
Random Hadith endpoint showing 404 ERROR

### ISSUE THREAD

**Issue by iMJ007** [sunnah-com/api#147]
Assalamualaikum,

The Random hadith endpoint i.e `GET
/hadiths/random` has been giving the following error message in response to the request:

`{"error":{"details":"The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.","code":404}}`

Even the same response is being recieved on [documentation site](sunnah.api-docs.io) when trying there.

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullah

Sorry about that - it should be working now!

**Comment by iMJ007** [comment]
> Wa`alaykum ussalam warahmatullah
> 
> Sorry about that - it should be working now!

It's still not working, and giving the same error response as before i.e 404

**Comment by ahadith** [comment]
Ah you were right. It's fixed now - I just verified!

**Comment by iMJ007** [comment]
> Ah you were right. It's fixed now - I just verified!

Jazakallah khair. Its working now.
